# Generated by Django 5.1.3 on 2024-12-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('user_pass', models.CharField(max_length=255)),
                ('user_role', models.CharField(default='user', max_length=50)),
            ],
        ),
    ]
